create table if not exists public.marketplace_tokens (
  id bigint generated by default as identity primary key,
  name text not null,
  ticker text not null,
  contract_address text not null unique,
  pump_fun_url text not null,
  description text not null,
  image_url text not null default '',
  tone text not null default 'blue',
  created_at timestamptz not null default now()
);

alter table public.marketplace_tokens enable row level security;
